apiVersion: v1
data:
  ingressGateway: kubeflow/kubeflow-gateway
kind: ConfigMap
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/name: kfserving
  name: kfserving-config
  namespace: kubeflow
