apiVersion: v1
data:
  USERID_HEADER: kubeflow-userid
kind: ConfigMap
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/component: kfserving-models-web-app
    app.kubernetes.io/name: kfserving
    kustomize.component: kfserving-models-web-app
  name: kfserving-models-web-app-config-99hfgfg5f4
  namespace: kubeflow
